language: cpp
sudo: false

matrix:
  include:
    - os: linux
      compiler: g++-5
      env: MKOK_CXX=g++-5
    - os: linux
      compiler: g++-5
      env: MKOK_CXX=g++-5
           VALGRIND=yes
    - os: linux
      compiler: clang-3.6
      env: MKOK_CXX=clang++-3.6
    - os: linux
      compiler: clang-3.6
      env: MKOK_CXX=clang++-3.6
           VALGRIND=yes
    - os: linux
      compiler: g++-5
      env: COVERAGE=--enable-coverage
           GCOV=gcov-5
           MKOK_CXX=g++-5
           CXXFLAGS=-g
    - os: osx
      compiler: clang++
      env: CPPFLAGS=-I/usr/local/opt/openssl/include
           LDFLAGS=-L/usr/local/opt/openssl/lib

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-5
      - valgrind

install:
  - if [ "$MKOK_CXX" != "" ]; then export CXX=$MKOK_CXX; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install libevent;
    fi

before_script:
  - if [ "$GCOV" != "" ]; then pip install --user --upgrade cpp-coveralls; fi

script:
  - autoreconf -i
  - ./configure -q $COVERAGE
  - make check V=0
  - if [ "$VALGRIND" = "yes" ]; then
      make run-valgrind;
    fi

after_script:
  - if [ "$GCOV" != "" ]; then
      coveralls --gcov $(which $GCOV) --include include/mkok;
    fi
